import type { Assignment } from "./types";

const day = 86_400_000;
const due = (offset: number) => new Date(Date.now() + offset * day).toISOString();

export const demoAssignments: Assignment[] = [
  {
    id: "REA-FCT-MG-DEMO-001",
    projectId: "FCT-MG-DURUMI-001",
    projectName: "Durumi Solar Mini Grid Demo",
    programme: "DARES",
    component: "Mini Grid",
    contractor: "Veritas Demo Contractor",
    state: "FCT",
    lga: "Abuja Municipal Area Council",
    community: "Durumi",
    latitude: 9.0232043,
    longitude: 7.4518017,
    dueDate: due(1),
    status: "Assigned",
    syncStatus: "synced",
    officer: "Mustapha Aliyu",
  },
  {
    id: "REA-KN-MG-0142",
    projectName: "Kofar Ruwa Solar Mini Grid",
    programme: "NEP",
    component: "Mini Grid",
    contractor: "SunVolt Nigeria",
    state: "Kano",
    lga: "Kano Municipal",
    community: "Kofar Ruwa",
    latitude: 12.0022,
    longitude: 8.5919,
    dueDate: due(1),
    status: "Assigned",
    syncStatus: "synced",
    officer: "Amina Yusuf",
  },
  {
    id: "REA-KD-GE-0087",
    projectName: "Kawo Grid Extension",
    programme: "DARES",
    component: "Grid Extension",
    contractor: "NorthGrid EPC",
    state: "Kaduna",
    lga: "Kaduna North",
    community: "Kawo",
    latitude: 10.5601,
    longitude: 7.4388,
    dueDate: due(2),
    status: "Draft",
    syncStatus: "queued",
    officer: "Amina Yusuf",
    report: {
      values: { implementationStatus: "Ongoing", startYear: "2026", startMonth: "August" },
      evidence: [],
      communitySignatory: "",
      contractorSignatory: "",
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: "REA-KT-SAS-0034",
    projectName: "Kofar Sauri SAS Deployment",
    programme: "AMP",
    component: "SAS",
    contractor: "Apex Power Works",
    state: "Katsina",
    lga: "Katsina",
    community: "Kofar Sauri",
    latitude: 12.9908,
    longitude: 7.6018,
    dueDate: due(4),
    status: "Assigned",
    syncStatus: "synced",
    officer: "Amina Yusuf",
  },
  {
    id: "REA-JG-MG-0062",
    projectName: "Dutse Community Mini Grid",
    programme: "DARES",
    component: "Mini Grid",
    contractor: "Arewa Renewables",
    state: "Jigawa",
    lga: "Dutse",
    community: "Limawa",
    latitude: 11.7594,
    longitude: 9.3392,
    dueDate: due(-2),
    status: "Approved",
    syncStatus: "synced",
    officer: "Amina Yusuf",
  },
  {
    id: "REA-SO-GE-0021",
    projectName: "Wamakko Grid Extension",
    programme: "NEP",
    component: "Grid Extension",
    contractor: "Sahel Energy Services",
    state: "Sokoto",
    lga: "Wamakko",
    community: "Gidan Bubu",
    latitude: 13.0358,
    longitude: 5.0942,
    dueDate: due(-5),
    status: "Verified",
    syncStatus: "synced",
    officer: "Amina Yusuf",
  },
];
