import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Device from "expo-device";
import * as Haptics from "expo-haptics";
import * as Location from "expo-location";
import * as Network from "expo-network";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type PropsWithChildren } from "react";
import { canonicalJson, CONSULTANT_FIRM, deviceAudit, FORM_SCHEMA_VERSION, GEOFENCE_RADIUS_METRES, networkAudit, newSessionId, OFFICER_ID, sha256Text, timezone } from "./audit";
import { demoAssignments } from "./demoData";
import { distanceMetres, isWithinProjectGeofence } from "./domain";
import type { Assignment, EvidenceRecord, InspectionReport } from "./types";
import { apiArrival, apiAssignments, apiDraft, apiEvidence, apiLogin, apiSubmit } from "./api";

const ASSIGNMENTS_KEY = "veritas-field-assignments-v1";
const SESSION_KEY = "veritas-field-session-v1";
const OFFICER_NAME = "Amina Yusuf";
type SessionRecord = { officerName: string; officerId: string; consultantFirm: string; sessionId: string; signedInAt: string; apiToken?: string; apiExpiresAt?: string };
type ArrivalResult = { ok: true; distanceMetres: number } | { ok: false; message: string; distanceMetres?: number };
type ActionResult = { ok: boolean; message: string };
type StoreValue = { assignments: Assignment[]; officerName: string; officerId: string; consultantFirm: string; sessionId: string; signedIn: boolean; hydrated: boolean; isOnline: boolean; login: (email: string, password: string) => Promise<boolean>; logout: () => Promise<void>; verifyArrival: (assignmentId: string) => Promise<ArrivalResult>; saveDraft: (assignmentId: string, values: Record<string, string>, communitySignatory?: string, contractorSignatory?: string) => ActionResult; addEvidence: (assignmentId: string, evidence: EvidenceRecord) => ActionResult; submitReport: (assignmentId: string, values: Record<string, string>, communitySignatory: string, contractorSignatory: string) => Promise<ActionResult>; syncNow: () => Promise<void> };
const StoreContext = createContext<StoreValue | null>(null);

function sessionFromStorage(raw: string | null): SessionRecord | null { if (!raw) return null; if (raw === OFFICER_NAME) return { officerName: OFFICER_NAME, officerId: OFFICER_ID, consultantFirm: CONSULTANT_FIRM, sessionId: newSessionId(), signedInAt: new Date().toISOString() }; try { const parsed = JSON.parse(raw) as SessionRecord; return parsed.sessionId ? { ...parsed, officerId: parsed.officerId ?? OFFICER_ID, consultantFirm: parsed.consultantFirm ?? CONSULTANT_FIRM } : null; } catch { return null; } }
function updatedReport(item: Assignment, values: Record<string,string>, communitySignatory: string, contractorSignatory: string, now: string, actorId: string, actorName: string, consultantFirm: string, sessionId: string): InspectionReport { const device=deviceAudit(); const audit=item.report?.workflowAudit??[]; return { ...item.report, values, evidence:item.report?.evidence??[], communitySignatory, contractorSignatory, updatedAt:now, draftCreatedAt:item.report?.draftCreatedAt??now, lastAutosavedAt:now, formSchemaVersion:FORM_SCHEMA_VERSION, appVersion:device.appVersion, appBuild:device.appBuild, assignmentSnapshot:{ assignmentId:item.id, projectId:item.projectId??item.id, projectName:item.projectName, programme:item.programme, component:item.component, contractor:item.contractor }, officerAudit:{officerId:actorId,officerName:actorName,consultantFirm,sessionId}, deviceAudit:device, captureTimezone:timezone(), workflowAudit:item.report?.draftCreatedAt?audit:[...audit,{action:"draft-created",actorId,actorName,actorRole:"Field Officer",at:now}], syncAudit:{...item.report?.syncAudit,attempts:item.report?.syncAudit?.attempts??0,queuedAt:now} }; }

export function StoreProvider({children}:PropsWithChildren){
 const [assignments,setAssignments]=useState<Assignment[]>(demoAssignments); const [session,setSession]=useState<SessionRecord|null>(null); const [hydrated,setHydrated]=useState(false); const [isOnline,setIsOnline]=useState(true);
 useEffect(()=>{void Promise.all([AsyncStorage.getItem(ASSIGNMENTS_KEY),AsyncStorage.getItem(SESSION_KEY),Network.getNetworkStateAsync().catch(()=>null)]).then(([storedAssignments,storedSession,network])=>{if(storedAssignments){try{const parsed=JSON.parse(storedAssignments) as Assignment[];const missing=demoAssignments.filter(d=>!parsed.some(i=>i.id===d.id));setAssignments([...parsed,...missing]);}catch{setAssignments(demoAssignments);}}const s=sessionFromStorage(storedSession);setSession(s);if(s&&storedSession===OFFICER_NAME)void AsyncStorage.setItem(SESSION_KEY,JSON.stringify(s));setIsOnline(Boolean(network?.isConnected&&network.isInternetReachable!==false));setHydrated(true);}).catch(()=>{setAssignments(demoAssignments);setSession(null);setIsOnline(false);setHydrated(true);});},[]);
 useEffect(()=>{if(hydrated)void AsyncStorage.setItem(ASSIGNMENTS_KEY,JSON.stringify(assignments));},[assignments,hydrated]);
 useEffect(()=>{const timer=setInterval(()=>{void Network.getNetworkStateAsync().then(n=>setIsOnline(Boolean(n.isConnected&&n.isInternetReachable!==false))).catch(()=>undefined);},10000);return()=>clearInterval(timer);},[]);
 const login=useCallback(async(identifier:string,password:string)=>{try{const result=await apiLogin(identifier,password);if(result.user.role!=="field_officer")return false;const next:SessionRecord={officerName:result.user.name,officerId:result.user.id,consultantFirm:result.user.consultantFirm,sessionId:newSessionId(),signedInAt:new Date().toISOString(),apiToken:result.token,apiExpiresAt:result.expiresAt};const remote=await apiAssignments(result.token);if(remote.assignments.length)setAssignments(c=>[...c.filter(i=>i.officer!==next.officerName),...remote.assignments]);await AsyncStorage.setItem(SESSION_KEY,JSON.stringify(next));setSession(next);return true;}catch{return false;}},[]);
 const logout=useCallback(async()=>{await AsyncStorage.removeItem(SESSION_KEY);setSession(null);},[]);
 const verifyArrival=useCallback(async(assignmentId:string):Promise<ArrivalResult>=>{const a=assignments.find(i=>i.id===assignmentId);if(!a)return{ok:false,message:"Assignment not found."};const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=="granted")return{ok:false,message:"Location permission is required for arrival verification."};try{const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});const distance=distanceMetres(current.coords.latitude,current.coords.longitude,a.latitude,a.longitude);if(!isWithinProjectGeofence(distance,GEOFENCE_RADIUS_METRES))return{ok:false,distanceMetres:distance,message:`Verification blocked — you are ${Math.round(distance).toLocaleString()} m outside the project centre.`};const verifiedAt=new Date().toISOString();setAssignments(items=>items.map(i=>i.id===assignmentId?{...i,syncStatus:"queued",arrival:{latitude:current.coords.latitude,longitude:current.coords.longitude,distanceMetres:distance,verifiedAt,accuracyMetres:current.coords.accuracy,altitudeMetres:current.coords.altitude,headingDegrees:current.coords.heading,speedMetresPerSecond:current.coords.speed,mocked:current.mocked,geofenceRadiusMetres:GEOFENCE_RADIUS_METRES,timezone:timezone()}}:i));await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);return{ok:true,distanceMetres:distance};}catch{return{ok:false,message:"GPS could not determine your location. Turn on Location Services and try again."};}},[assignments]);
 const saveDraft=useCallback((assignmentId:string,values:Record<string,string>,communitySignatory="",contractorSignatory=""):ActionResult=>{const t=assignments.find(i=>i.id===assignmentId);if(!t?.arrival)return{ok:false,message:"Verify GPS arrival to unlock and save this form."};if(["Submitted","Approved","Verified"].includes(t.status))return{ok:false,message:"This inspection is locked."};const now=new Date().toISOString();setAssignments(items=>items.map(i=>i.id===assignmentId?{...i,status:"Draft",syncStatus:"queued",report:updatedReport(i,values,communitySignatory,contractorSignatory,now,session?.officerId??OFFICER_ID,session?.officerName??OFFICER_NAME,session?.consultantFirm??CONSULTANT_FIRM,session?.sessionId??"")}:i));return{ok:true,message:"Draft saved on this device."};},[assignments,session]);
 const addEvidence=useCallback((assignmentId:string,evidence:EvidenceRecord):ActionResult=>{const t=assignments.find(i=>i.id===assignmentId);if(!t?.arrival)return{ok:false,message:"Verify GPS arrival before capturing evidence."};const now=new Date().toISOString();setAssignments(items=>items.map(i=>{if(i.id!==assignmentId)return i;const report=updatedReport(i,i.report?.values??{},i.report?.communitySignatory??"",i.report?.contractorSignatory??"",now,session?.officerId??OFFICER_ID,session?.officerName??OFFICER_NAME,session?.consultantFirm??CONSULTANT_FIRM,session?.sessionId??"");return{...i,status:i.status==="Assigned"?"Draft":i.status,syncStatus:"queued",report:{...report,evidence:[...report.evidence,evidence]}};}));return{ok:true,message:"Evidence secured."};},[assignments,session]);
 const submitReport=useCallback(async(assignmentId:string,values:Record<string,string>,communitySignatory:string,contractorSignatory:string):Promise<ActionResult>=>{const a=assignments.find(i=>i.id===assignmentId);if(!a?.arrival)return{ok:false,message:"Verify arrival with GPS before submission."};const evidence=a.report?.evidence??[];if(!evidence.length)return{ok:false,message:"Capture at least one evidence photo or video."};if(!communitySignatory.trim()||!contractorSignatory.trim())return{ok:false,message:"Add both representative signatories."};const now=new Date().toISOString();const signatures={community:{name:communitySignatory.trim(),role:"Community representative" as const,signedAt:now,latitude:a.arrival.latitude,longitude:a.arrival.longitude,method:"typed-name" as const},contractor:{name:contractorSignatory.trim(),role:"Contractor representative" as const,signedAt:now,latitude:a.arrival.latitude,longitude:a.arrival.longitude,method:"typed-name" as const}};const formIntegrityHash=await sha256Text(canonicalJson({assignmentId,values,evidence:evidence.map(i=>i.integrityHash??i.id),signatures}));const signatureIntegrityHash=await sha256Text(canonicalJson(signatures));setAssignments(items=>items.map(i=>i.id===assignmentId?{...i,status:"Submitted",syncStatus:"queued",report:{...updatedReport(i,values,communitySignatory.trim(),contractorSignatory.trim(),now,session?.officerId??OFFICER_ID,session?.officerName??OFFICER_NAME,session?.consultantFirm??CONSULTANT_FIRM,session?.sessionId??""),evidence,submittedAt:now,lockedAt:now,formIntegrityAlgorithm:"SHA-256",formIntegrityHash,signatureIntegrityHash,communitySignature:signatures.community,contractorSignature:signatures.contractor,workflowAudit:[...(i.report?.workflowAudit??[]),{action:"submitted",actorId:session?.officerId??OFFICER_ID,actorName:session?.officerName??OFFICER_NAME,actorRole:"Field Officer",at:now}]}}:i));void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);return{ok:true,message:"Inspection submitted for Consultant Admin review."};},[assignments,session]);
 const syncNow=useCallback(async()=>{if(!isOnline||!session?.apiToken)return;const network=await networkAudit();const queue=assignments.filter(i=>i.syncStatus==="queued"||i.syncStatus==="failed");for(const item of queue){const startedAt=new Date().toISOString();setAssignments(current=>current.map(c=>c.id===item.id?{...c,syncStatus:"uploading",report:c.report?{...c.report,syncAudit:{...c.report.syncAudit,...network,attempts:(c.report.syncAudit?.attempts??0)+1,uploadStartedAt:startedAt}}:c.report}:c));try{if(item.arrival)await apiArrival(session.apiToken,item.id,item.arrival);if(item.report){for(const evidence of item.report.evidence)await apiEvidence(session.apiToken,item.id,evidence);if(item.status==="Submitted")await apiSubmit(session.apiToken,item.id,item.report);else await apiDraft(session.apiToken,item.id,item.report);}const completedAt=new Date().toISOString();setAssignments(current=>current.map(c=>c.id===item.id?{...c,syncStatus:"synced",report:c.report?{...c.report,syncAudit:{...c.report.syncAudit,attempts:c.report.syncAudit?.attempts??1,uploadCompletedAt:completedAt,serverReceivedAt:completedAt,lastError:undefined}}:c.report}:c));}catch(error){setAssignments(current=>current.map(c=>c.id===item.id?{...c,syncStatus:"failed",report:c.report?{...c.report,syncAudit:{...c.report.syncAudit,attempts:c.report.syncAudit?.attempts??1,lastError:error instanceof Error?error.message:"Synchronization failed."}}:c.report}:c));}}const remote=await apiAssignments(session.apiToken).catch(()=>null);if(remote?.assignments.length)setAssignments(current=>{const localById=new Map(current.map(i=>[i.id,i]));const merged=remote.assignments.map(i=>{const local=localById.get(i.id);return{...i,report:local?.report??i.report,arrival:i.arrival??local?.arrival,syncStatus:"synced" as const};});return[...current.filter(i=>i.officer!==session.officerName),...merged];});},[isOnline,session,assignments]);
 const value=useMemo<StoreValue>(()=>({assignments:assignments.filter(i=>i.officer===(session?.officerName??OFFICER_NAME)),officerName:session?.officerName??OFFICER_NAME,officerId:session?.officerId??OFFICER_ID,consultantFirm:session?.consultantFirm??CONSULTANT_FIRM,sessionId:session?.sessionId??"",signedIn:Boolean(session),hydrated,isOnline,login,logout,verifyArrival,saveDraft,addEvidence,submitReport,syncNow}),[assignments,session,hydrated,isOnline,login,logout,verifyArrival,saveDraft,addEvidence,submitReport,syncNow]);return <StoreContext.Provider value={value}>{children}</StoreContext.Provider>;
}
export function useStore(){const value=useContext(StoreContext);if(!value)throw new Error("useStore must be used inside StoreProvider");return value;}
export function deviceName(){return Device.modelName??Device.deviceName??"Android device";}
