import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Download, FileClock, Search, ShieldAlert } from "lucide-react";
import { defaultAuditEvents, readAuditEvents, type AuditEvent } from "../lib/rea-admin";

export default function ReaAuditTrail(){
 const[events,setEvents]=useState<AuditEvent[]>(readAuditEvents); const[query,setQuery]=useState(""); const[category,setCategory]=useState("All activity");
 useEffect(()=>{const refresh=()=>setEvents(readAuditEvents());window.addEventListener("veritas-audit-updated",refresh);return()=>window.removeEventListener("veritas-audit-updated",refresh)},[]);
 const visible=useMemo(()=>events.filter(e=>`${e.actor} ${e.action} ${e.target} ${e.details}`.toLowerCase().includes(query.toLowerCase())&&(category==="All activity"||e.category===category)),[events,query,category]);
 const exportCsv=()=>{const rows=[["Timestamp","Actor","Category","Action","Target","Details","Severity"],...visible.map(e=>[e.timestamp,e.actor,e.category,e.action,e.target,e.details,e.severity])];const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="veritas-audit-trail.csv";a.click();URL.revokeObjectURL(a.href)};
 return <div className="space-y-4 pb-8 pt-4"><section className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><FileClock className="h-5 w-5 text-[#08733f]"/><h2 className="text-xl font-bold text-[#173b2a]">Audit Trail</h2></div><p className="mt-1 text-xs text-slate-500">Trace account, access, verification and system activity across Veritas.</p></div><button onClick={exportCsv} className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 text-xs font-bold text-slate-700 hover:bg-slate-50"><Download className="h-4 w-4"/>Export audit log</button></section>
 <section className="grid gap-3 sm:grid-cols-4"><Stat label="Recorded events" value={events.length} icon={FileClock} c="text-blue-700 bg-blue-50"/><Stat label="Today" value={events.filter(e=>new Date(e.timestamp).toDateString()===new Date().toDateString()).length} icon={Clock3} c="text-violet-700 bg-violet-50"/><Stat label="Successful" value={events.filter(e=>e.severity==="Success").length} icon={CheckCircle2} c="text-emerald-700 bg-emerald-50"/><Stat label="Warnings" value={events.filter(e=>e.severity==="Warning"||e.severity==="Critical").length} icon={ShieldAlert} c="text-amber-700 bg-amber-50"/></section>
 <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actor, action, target or detail" className="h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-xs outline-none focus:border-[#08733f]"/></div><select value={category} onChange={e=>setCategory(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-600"><option>All activity</option>{["Authentication","User Management","Access Control","Claims","Verification","System"].map(x=><option key={x}>{x}</option>)}</select></div><div className="divide-y divide-slate-100">{visible.map(e=><div key={e.id} className="grid gap-3 p-4 transition hover:bg-slate-50/70 md:grid-cols-[150px_1fr_140px] md:items-center"><div><p className="text-[10px] font-semibold text-slate-500">{new Date(e.timestamp).toLocaleDateString("en-NG",{day:"2-digit",month:"short",year:"numeric"})}</p><p className="mt-0.5 text-[10px] text-slate-400">{new Date(e.timestamp).toLocaleTimeString("en-NG",{hour:"2-digit",minute:"2-digit"})}</p></div><div className="flex gap-3"><span className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${e.severity==="Success"?"bg-emerald-50 text-emerald-700":e.severity==="Warning"||e.severity==="Critical"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700"}`}>{e.severity==="Warning"||e.severity==="Critical"?<AlertTriangle className="h-4 w-4"/>:<CheckCircle2 className="h-4 w-4"/>}</span><div><p className="text-xs font-bold text-slate-800">{e.action} <span className="font-normal text-slate-400">·</span> {e.target}</p><p className="mt-1 text-[10px] leading-4 text-slate-500">{e.details}</p><p className="mt-1 text-[10px] font-semibold text-[#08733f]">{e.actor}</p></div></div><div className="md:text-right"><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-600">{e.category}</span></div></div>)}{visible.length===0&&<div className="p-12 text-center text-xs text-slate-500">No audit events match the current filters.</div>}</div></section></div>
}
function Stat({label,value,icon:Icon,c}:{label:string,value:number,icon:any,c:string}){return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`flex h-8 w-8 items-center justify-center rounded-lg ${c}`}><Icon className="h-4 w-4"/></div><p className="mt-3 text-2xl font-bold text-[#173b2a]">{value}</p><p className="text-[10px] text-slate-500">{label}</p></div>}
