import { useMemo, useState } from "react";
import { Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Line,Pie,PieChart,PolarAngleAxis,RadialBar,RadialBarChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { Activity,ArrowUpRight,BarChart3,CheckCircle2,Gauge,Home,Layers3,MapPin,Sparkles,TrendingUp,Zap } from "lucide-react";
import type { Project } from "../lib/dashboard-data";
type Props={projects:Project[]}; type Period="All"|"H1"|"H2";
const palette=["#08733f","#4f7cff","#f59e0b","#8b5cf6","#06b6d4","#ef6c8f"];
const months=["January 2024","February 2024","March 2024","April 2024","May 2024","June 2024","July 2024","August 2024","September 2024","October 2024","November 2024","December 2024"];
const tones=[
["from-emerald-50","bg-emerald-100 text-emerald-700"],["from-blue-50","bg-blue-100 text-blue-700"],["from-amber-50","bg-amber-100 text-amber-700"],["from-violet-50","bg-violet-100 text-violet-700"],["from-cyan-50","bg-cyan-100 text-cyan-700"]];
const compact=(v:number)=>Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(v);
export default function ReaAnalyticsDashboard({projects}:Props){
 const[period,setPeriod]=useState<Period>("All"); const[programme,setProgramme]=useState("All Programmes");
 const programmes=useMemo(()=>["All Programmes",...Array.from(new Set(projects.map(x=>x.programme)))],[projects]);
 const filtered=useMemo(()=>{const allowed=period==="H1"?months.slice(0,6):period==="H2"?months.slice(6):months;return projects.filter(x=>allowed.includes(x.month)&&(programme==="All Programmes"||x.programme===programme));},[period,programme,projects]);
 const totals=useMemo(()=>{const verified=filtered.filter(x=>x.verified).length;return{projects:filtered.length,verified,rate:filtered.length?Math.round(verified/filtered.length*100):0,capacity:filtered.reduce((s,x)=>s+x.kw,0)/1000,households:filtered.reduce((s,x)=>s+x.households,0)}},[filtered]);
 const monthly=useMemo(()=>months.map(m=>{const r=filtered.filter(x=>x.month===m),v=r.filter(x=>x.verified).length;return{month:m.slice(0,3),projects:r.length,verified:v}}).filter(x=>x.projects),[filtered]);
 const programmeData=useMemo(()=>Array.from(new Set(filtered.map(x=>x.programme))).map(name=>{const r=filtered.filter(x=>x.programme===name),v=r.filter(x=>x.verified).length;return{name,projects:r.length,rate:r.length?Math.round(v/r.length*100):0}}).sort((a,b)=>b.projects-a.projects),[filtered]);
 const components=useMemo(()=>Array.from(new Set(filtered.map(x=>x.component))).map(name=>({name,value:filtered.filter(x=>x.component===name).length})).sort((a,b)=>b.value-a.value),[filtered]);
 const states=useMemo(()=>Array.from(new Set(filtered.map(x=>x.state))).map(state=>{const r=filtered.filter(x=>x.state===state),v=r.filter(x=>x.verified).length;return{state,projects:r.length,rate:r.length?Math.round(v/r.length*100):0}}).sort((a,b)=>b.projects-a.projects).slice(0,8),[filtered]);
 const best=states.slice().sort((a,b)=>b.rate-a.rate)[0],avg=totals.projects?totals.capacity/totals.projects:0;
 const kpis=[{label:"Projects",value:totals.projects.toLocaleString(),detail:"Active portfolio",icon:Layers3},{label:"Installed Capacity",value:`${totals.capacity.toFixed(1)} MW`,detail:`${avg.toFixed(2)} MW average`,icon:Zap},{label:"Households Reached",value:compact(totals.households),detail:totals.households.toLocaleString(),icon:Home},{label:"Verified",value:totals.verified.toLocaleString(),detail:`${totals.rate}% verification rate`,icon:CheckCircle2},{label:"Top Performing State",value:best?.state??"—",detail:best?`${best.rate}% verified`:"No matching data",icon:MapPin}];
 return <div className="space-y-4 pb-8 pt-4">
  <section className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-[0_4px_18px_rgba(15,23,42,.04)] lg:flex-row lg:items-center lg:justify-between">
   <div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-100 via-blue-100 to-violet-100 text-violet-700"><Sparkles className="h-5 w-5"/></span><div><h2 className="text-xl font-bold text-[#173b2a]">National Delivery Analytics</h2><p className="mt-0.5 text-xs text-slate-500">Live intelligence across delivery, capacity and verification performance.</p></div></div>
   <div className="flex flex-wrap gap-2"><select value={programme} onChange={e=>setProgramme(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 outline-none focus:border-[#08733f]">{programmes.map(x=><option key={x}>{x}</option>)}</select><div className="flex rounded-lg border border-slate-200 bg-slate-50 p-1">{(["All","H1","H2"] as Period[]).map(x=><button key={x} onClick={()=>setPeriod(x)} className={`rounded-md px-3 py-2 text-[11px] font-bold transition-all duration-300 ${period===x?"bg-white text-[#08733f] shadow-sm":"text-slate-500 hover:text-slate-800"}`}>{x==="All"?"Full year":x}</button>)}</div></div>
  </section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(({label,value,detail,icon:Icon},i)=><article key={label} className={`group relative overflow-hidden rounded-xl border border-slate-200 bg-gradient-to-br ${tones[i][0]} to-white p-4 shadow-sm transition-all duration-500 hover:-translate-y-1 hover:shadow-xl`}><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-white/70 blur-xl transition-transform duration-700 group-hover:scale-150"/><div className="relative flex justify-between"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tones[i][1]} transition-all duration-500 group-hover:rotate-6 group-hover:scale-110`}><Icon className="h-5 w-5"/></div><ArrowUpRight className="h-4 w-4 text-slate-300 transition-transform duration-300 group-hover:-translate-y-1 group-hover:translate-x-1"/></div><p className="relative mt-4 text-[11px] font-semibold text-slate-500">{label}</p><p className="relative mt-1 text-xl font-bold text-[#173b2a]">{value}</p><p className="relative mt-1 text-[10px] text-slate-500">{detail}</p></article>)}</section>
  <section className="grid gap-4 xl:grid-cols-[1.55fr_.85fr]">
   <article className="rounded-xl border border-slate-200 bg-gradient-to-b from-white to-blue-50/30 p-5 shadow-sm"><div className="flex justify-between"><div><div className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-blue-600"/><h3 className="text-sm font-bold text-[#173b2a]">Delivery Momentum</h3></div><p className="mt-1 text-[11px] text-slate-500">Monthly projects and verified reports</p></div><span className="h-fit rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-700">Live trend</span></div><div className="mt-4 h-[320px]"><ResponsiveContainer><AreaChart data={monthly} margin={{top:8,right:10,left:-20,bottom:0}}><defs><linearGradient id="pf" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4f7cff" stopOpacity={.35}/><stop offset="1" stopColor="#4f7cff" stopOpacity={.02}/></linearGradient><linearGradient id="vf" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#12a36d" stopOpacity={.25}/><stop offset="1" stopColor="#12a36d" stopOpacity={.01}/></linearGradient></defs><CartesianGrid strokeDasharray="4 4" stroke="#edf0f5" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:10}}/><YAxis axisLine={false} tickLine={false} allowDecimals={false} tick={{fontSize:10}}/><Tooltip contentStyle={{borderRadius:12,borderColor:"#e1e5ec",fontSize:11}}/><Area type="monotone" dataKey="projects" stroke="#4f7cff" strokeWidth={3} fill="url(#pf)" animationDuration={1200}/><Area type="monotone" dataKey="verified" stroke="#12a36d" strokeWidth={2.3} fill="url(#vf)" animationDuration={1600}/></AreaChart></ResponsiveContainer></div></article>
   <article className="relative overflow-hidden rounded-xl border border-slate-200 bg-gradient-to-br from-white to-amber-50 p-5 shadow-sm"><div className="absolute -right-12 -top-12 h-36 w-36 rounded-full bg-amber-100/60 blur-2xl"/><div className="relative flex items-center gap-2"><Gauge className="h-4 w-4 text-amber-600"/><h3 className="text-sm font-bold text-[#173b2a]">Verification Health</h3></div><p className="relative mt-1 text-[11px] text-slate-500">Share of reports fully verified</p><div className="relative h-[230px]"><ResponsiveContainer><RadialBarChart innerRadius="72%" outerRadius="100%" data={[{value:totals.rate}]} startAngle={220} endAngle={-40}><PolarAngleAxis type="number" domain={[0,100]} tick={false}/><RadialBar background={{fill:"#f5f0e8"}} dataKey="value" fill="#f59e0b" cornerRadius={12} animationDuration={1500}/></RadialBarChart></ResponsiveContainer><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><p className="text-4xl font-bold text-[#173b2a]">{totals.rate}%</p><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Verified</p></div></div></div><div className="relative grid grid-cols-2 gap-2"><div className="rounded-lg bg-emerald-50 p-3 transition hover:scale-[1.02]"><p className="text-[10px] text-slate-500">Verified</p><p className="text-lg font-bold text-emerald-700">{totals.verified}</p></div><div className="rounded-lg bg-rose-50 p-3 transition hover:scale-[1.02]"><p className="text-[10px] text-slate-500">Outstanding</p><p className="text-lg font-bold text-rose-600">{totals.projects-totals.verified}</p></div></div></article>
  </section>
  <section className="grid gap-4 xl:grid-cols-3"><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><div className="flex items-center gap-2"><BarChart3 className="h-4 w-4 text-violet-600"/><h3 className="text-sm font-bold text-[#173b2a]">Programme Performance</h3></div><p className="mt-1 text-[11px] text-slate-500">Portfolio volume with verification overlay</p><div className="mt-4 h-[280px]"><ResponsiveContainer><BarChart data={programmeData} margin={{left:-22}}><defs><linearGradient id="bf" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#8b5cf6"/><stop offset="1" stopColor="#4f7cff"/></linearGradient></defs><CartesianGrid strokeDasharray="4 4" stroke="#edf0f5" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:10}}/><YAxis yAxisId="c" axisLine={false} tickLine={false} tick={{fontSize:10}}/><YAxis yAxisId="r" orientation="right" domain={[0,100]} hide/><Tooltip contentStyle={{borderRadius:12,fontSize:11}}/><Bar yAxisId="c" dataKey="projects" fill="url(#bf)" radius={[8,8,0,0]} animationDuration={1100}/><Line yAxisId="r" dataKey="rate" stroke="#f59e0b" strokeWidth={2.4} dot={{r:3,fill:"#f59e0b"}} animationDuration={1500}/></BarChart></ResponsiveContainer></div></article>
   <article className="rounded-xl border border-slate-200 bg-gradient-to-br from-white to-violet-50/50 p-5 shadow-sm"><div className="flex items-center gap-2"><Layers3 className="h-4 w-4 text-cyan-600"/><h3 className="text-sm font-bold text-[#173b2a]">Component Mix</h3></div><p className="mt-1 text-[11px] text-slate-500">Distribution across delivery components</p><div className="h-[220px]"><ResponsiveContainer><PieChart><Pie data={components} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={4} animationDuration={1400}>{components.map((x,i)=><Cell key={x.name} fill={palette[i%palette.length]}/>)}</Pie><Tooltip contentStyle={{borderRadius:12,fontSize:11}}/></PieChart></ResponsiveContainer></div><div className="space-y-2">{components.map((x,i)=><div key={x.name} className="flex items-center gap-2 text-[10px]"><span className="h-2.5 w-2.5 rounded-sm" style={{backgroundColor:palette[i%palette.length]}}/><span className="flex-1 truncate text-slate-600">{x.name}</span><strong>{x.value}</strong></div>)}</div></article></section>
  <section className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-rose-500"/><h3 className="text-sm font-bold text-[#173b2a]">Leading States</h3></div><p className="mt-1 text-[11px] text-slate-500">Top states by project activity</p><div className="mt-4 h-[300px]"><ResponsiveContainer><BarChart data={states} layout="vertical" margin={{left:10}}><defs><linearGradient id="sf" x1="0" y1="0" x2="1" y2="0"><stop stopColor="#ef6c8f"/><stop offset="1" stopColor="#f59e0b"/></linearGradient></defs><XAxis type="number" hide/><YAxis type="category" dataKey="state" axisLine={false} tickLine={false} width={62} tick={{fontSize:10}}/><Tooltip contentStyle={{borderRadius:12,fontSize:11}}/><Bar dataKey="projects" fill="url(#sf)" radius={[0,8,8,0]} animationDuration={1250}/></BarChart></ResponsiveContainer></div></article><article className="group relative overflow-hidden rounded-xl border border-slate-200 bg-gradient-to-br from-blue-50 via-white to-rose-50 p-5 shadow-sm"><div className="absolute -bottom-12 -right-12 h-40 w-40 rounded-full bg-violet-100/70 blur-2xl transition-transform duration-1000 group-hover:scale-125"/><div className="relative flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-blue-600 to-violet-600 text-white shadow-lg transition-all duration-500 group-hover:rotate-6 group-hover:scale-110"><Activity className="h-5 w-5"/></div><h3 className="relative mt-5 text-lg font-bold text-[#173b2a]">Performance Signal</h3><p className="relative mt-2 text-sm leading-6 text-slate-600">{totals.rate>=70?"Verification performance is strong across the selected portfolio.":totals.rate>=50?"Verification is progressing, with a meaningful outstanding review queue.":"Verification backlog is elevated and should be prioritised for management attention."}</p><div className="relative mt-5 rounded-xl border border-white bg-white/80 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Current rate</p><div className="flex items-end justify-between"><p className="mt-1 text-3xl font-bold text-violet-700">{totals.rate}%</p><TrendingUp className="h-8 w-8 text-violet-300"/></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 via-violet-500 to-rose-400 transition-all duration-1000" style={{width:`${totals.rate}%`}}/></div></div></article></section>
 </div>;
}
