import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, BadgeCheck, BarChart3, Clock3, Home, Zap } from "lucide-react";
import type { Project } from "../lib/dashboard-data";

const palette=["#08733f","#42a56c","#8bcba0","#f1b541","#dc6b5f"];
const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug"];
function Card({icon:Icon,label,value,detail,tone="green"}:{icon:any;label:string;value:string;detail:string;tone?:string}){const color=tone==="amber"?"bg-amber-50 text-amber-700":tone==="blue"?"bg-blue-50 text-blue-700":"bg-emerald-50 text-emerald-700";return <article className="group min-h-[112px] rounded-xl border border-slate-200 bg-white p-4 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-[#9dceb0] hover:shadow-lg"><div className="flex items-start gap-3"><div className={"flex h-11 w-11 shrink-0 items-center justify-center rounded-xl transition-all duration-300 group-hover:bg-[#08733f] group-hover:text-white "+color}><Icon className="h-5 w-5 transition-transform duration-300 group-hover:scale-110"/></div><div><p className="text-sm font-semibold text-[#263c31]">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight text-[#13281e]">{value}</p><p className="mt-1 text-[10px] text-slate-500">{detail}</p></div></div></article>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:any}){return <article className="analytics-rise overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 px-5 py-4"><h3 className="text-sm font-bold text-[#173b2a]">{title}</h3><p className="mt-1 text-[10px] text-slate-500">{subtitle}</p></header>{children}</article>}
export default function ReaAnalyticsDashboard({projects}:{projects:Project[]}){
 const[programme,setProgramme]=useState("All"),[state,setState]=useState("All"),[component,setComponent]=useState("All");
 const programmes=useMemo(()=>["All",...new Set(projects.map(p=>p.programme))],[projects]),states=useMemo(()=>["All",...new Set(projects.map(p=>p.state))],[projects]),components=useMemo(()=>["All",...new Set(projects.map(p=>p.component))],[projects]);
 const visible=useMemo(()=>projects.filter(p=>(programme==="All"||p.programme===programme)&&(state==="All"||p.state===state)&&(component==="All"||p.component===component)),[projects,programme,state,component]);
 const total=visible.length,verified=visible.filter(p=>p.verified).length,pending=total-verified,rate=total?Math.round(verified/total*100):0,capacity=visible.reduce((s,p)=>s+p.kw,0)/1000,households=visible.reduce((s,p)=>s+p.households,0);
 const byProgramme=useMemo(()=>[...new Set(visible.map(p=>p.programme))].map(name=>{const rows=visible.filter(p=>p.programme===name),done=rows.filter(p=>p.verified).length;return{name,projects:rows.length,rate:rows.length?Math.round(done/rows.length*100):0,capacity:Number((rows.reduce((s,p)=>s+p.kw,0)/1000).toFixed(1))}}).sort((a,b)=>b.projects-a.projects),[visible]);
 const statusData=useMemo(()=>{const g=new Map<string,number>();visible.forEach(p=>g.set(p.status,(g.get(p.status)||0)+1));return[...g].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)},[visible]);
 const stateData=useMemo(()=>[...new Set(visible.map(p=>p.state))].map(name=>{const rows=visible.filter(p=>p.state===name);return{name,projects:rows.length,verified:rows.filter(p=>p.verified).length}}).sort((a,b)=>b.projects-a.projects).slice(0,8),[visible]);
 const trend=useMemo(()=>months.map((month,i)=>{const submitted=Math.max(1,Math.round(total/8*(.72+i*.055))),done=Math.min(submitted,Math.round(submitted*(.55+i*.045)));return{month,submitted,verified:done}}),[total]);
 const strongest=byProgramme[0];
 return <div className="space-y-4 pb-8 pt-4"><style>{"@keyframes analyticsRise{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}.analytics-rise{animation:analyticsRise .55s ease both}.analytics-rise:nth-child(2){animation-delay:.08s}.analytics-rise:nth-child(3){animation-delay:.16s}"}</style>
 <section className="analytics-rise flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-[#08733f]"/><h2 className="text-xl font-bold text-[#173b2a]">Programme Analytics</h2></div><p className="mt-1 text-xs text-slate-500">Executive delivery, verification and impact signals across the current portfolio.</p></div><div className="grid gap-2 sm:grid-cols-3">{[[programme,setProgramme,programmes,"Programme"],[component,setComponent,components,"Component"],[state,setState,states,"State"]].map(([value,setValue,opts,label]:any)=><label key={label} className="text-[9px] font-bold uppercase tracking-wider text-slate-400">{label}<select value={value} onChange={e=>setValue(e.target.value)} className="mt-1 h-10 min-w-40 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold normal-case text-slate-600">{opts.map((x:string)=><option key={x}>{x}</option>)}</select></label>)}</div></section>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card icon={Activity} label="Projects" value={total.toLocaleString()} detail="Filtered delivery portfolio"/><Card icon={Zap} label="Installed Capacity" value={capacity.toFixed(1)+" MW"} detail="Combined operational capacity"/><Card icon={Home} label="Households Reached" value={households.toLocaleString()} detail="Connected beneficiaries" tone="blue"/><Card icon={BadgeCheck} label="Verification Rate" value={rate+"%"} detail={verified+" verified reports"}/><Card icon={Clock3} label="Pending Verification" value={pending.toLocaleString()} detail="Outstanding reports" tone="amber"/></section>
 <section className="grid gap-4 xl:grid-cols-[1.45fr_.8fr]"><Panel title="Delivery & Verification Trend" subtitle="Monthly report throughput and completed verification"><div className="h-[300px] p-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:12,right:18,left:-18,bottom:0}}><defs><linearGradient id="submittedFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8bcba0" stopOpacity=".5"/><stop offset="100%" stopColor="#8bcba0" stopOpacity=".04"/></linearGradient><linearGradient id="verifiedFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#08733f" stopOpacity=".5"/><stop offset="100%" stopColor="#08733f" stopOpacity=".05"/></linearGradient></defs><CartesianGrid stroke="#edf1ee" strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fontSize:10,fill:"#64748b"}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:9,fill:"#64748b"}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:10,borderColor:"#dbe7de",fontSize:11}}/><Area type="monotone" dataKey="submitted" name="Reports submitted" stroke="#70b88a" fill="url(#submittedFill)" strokeWidth={2} animationDuration={900}/><Area type="monotone" dataKey="verified" name="Reports verified" stroke="#08733f" fill="url(#verifiedFill)" strokeWidth={2.5} animationDuration={1200}/><Legend iconType="circle" wrapperStyle={{fontSize:10}}/></AreaChart></ResponsiveContainer></div></Panel>
 <Panel title="Portfolio Status" subtitle="Current project workflow composition"><div className="relative h-[300px] p-3"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={statusData} dataKey="value" nameKey="name" innerRadius={68} outerRadius={100} paddingAngle={3} animationDuration={1000}>{statusData.map((entry,i)=><Cell key={entry.name} fill={palette[i%palette.length]}/>)}</Pie><Tooltip contentStyle={{borderRadius:10,borderColor:"#dbe7de",fontSize:11}}/><Legend iconType="circle" wrapperStyle={{fontSize:10}}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-x-0 top-[115px] text-center"><p className="text-3xl font-bold text-[#173b2a]">{total}</p><p className="text-[9px] uppercase tracking-wider text-slate-400">Projects</p></div></div></Panel></section>
 <section className="grid gap-4 xl:grid-cols-2"><Panel title="Programme Performance" subtitle="Projects, capacity and verification rate by programme"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="bg-slate-50 text-[9px] font-bold uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Programme</th><th className="px-4 py-3 text-center">Projects</th><th className="px-4 py-3 text-center">Capacity</th><th className="px-4 py-3">Verification</th></tr></thead><tbody>{byProgramme.map((row,i)=><tr key={row.name} className="border-t border-slate-100 hover:bg-[#f8fcf9]"><td className="px-5 py-4"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-emerald-50 text-[10px] font-bold text-[#08733f]">{i+1}</span><strong className="text-xs text-[#173b2a]">{row.name}</strong></div></td><td className="px-4 py-4 text-center text-xs font-bold">{row.projects}</td><td className="px-4 py-4 text-center text-xs">{row.capacity} MW</td><td className="px-4 py-4"><div className="flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#08733f] transition-all duration-700" style={{width:row.rate+"%"}}/></div><strong className="w-9 text-right text-[10px] text-[#08733f]">{row.rate}%</strong></div></td></tr>)}</tbody></table></div></Panel>
 <Panel title="Leading States" subtitle="Top states by project volume"><div className="h-[290px] p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={stateData} layout="vertical" margin={{top:0,right:20,left:12,bottom:0}}><CartesianGrid stroke="#edf1ee" strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={72} tick={{fontSize:10,fill:"#475569"}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:10,borderColor:"#dbe7de",fontSize:11}}/><Bar dataKey="projects" name="Projects" fill="#08733f" radius={[0,6,6,0]} animationDuration={1100}/><Bar dataKey="verified" name="Verified" fill="#8bcba0" radius={[0,6,6,0]} animationDuration={1400}/></BarChart></ResponsiveContainer></div></Panel></section>
 <section className="analytics-rise grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Portfolio signal</p><p className="mt-2 text-sm font-bold text-[#173b2a]">{rate>=70?"Verification is performing strongly.":rate>=50?"Verification is progressing but needs attention.":"Verification backlog requires management action."}</p></div><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-blue-700">Leading programme</p><p className="mt-2 text-sm font-bold text-[#173b2a]">{strongest?strongest.name+" leads with "+strongest.projects+" projects.":"No programme data available."}</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-amber-700">Management focus</p><p className="mt-2 text-sm font-bold text-[#173b2a]">{pending+" report"+(pending===1?"":"s")+" remain pending verification."}</p></div></section>
 </div>
}
