import { useMemo, useRef, useState } from "react";
import {
  AlertTriangle, ArrowLeft, BadgeCheck, Banknote, CalendarDays, CheckCircle2,
  ChevronRight, CircleDollarSign, Cloud, Download, FileSpreadsheet, Filter,
  MapPin, PackageCheck, Phone, RefreshCw, Search, ShieldCheck, Upload,
  UserRoundCheck, WifiOff, XCircle, Zap,
} from "lucide-react";
import { readConsultants } from "../lib/consultants";

type ClaimStatus="Uploaded"|"Assigned for Verification"|"Field Inspection Complete"|"Consultant Reviewed"|"REA Verified"|"Disputed"|"Rejected";
type AuditStatus="Pending Audit"|"In Review"|"Approved"|"Flagged"|"Rejected";
type Claim={
 id:string;customerId:string;customerName:string;gender:string;customerCategory:string;customerType:string;
 address:string;state:string;lga:string;phone:string;alternatePhone:string;latitude:number;longitude:number;
 paymentDate:string;model:string;pvCapacity:number;paymentType:string;retailCost:number;costToEndUser:number;
 paymentPlan:string;downpayment:number;installment:number;submittedDate:string;auditStatus:AuditStatus;
 auditorNotes:string;approvedDate:string;paidDate:string;uploadDate:string;contractor:string;
 consultant:string;status:ClaimStatus;
};
type ImportField={key:keyof Claim;label:string;managed?:boolean};
type StageRow=Claim&{row:number;validity:"Valid"|"Flagged"|"Error";issues:string[]};
const storageKey="veritas-rea-dares-claims-v2";
const apiBase=(import.meta.env.VITE_REA_CLAIMS_API_URL as string|undefined)?.replace(/\/$/,"")||"";
const lifecycle:ClaimStatus[]=["Uploaded","Assigned for Verification","Field Inspection Complete","Consultant Reviewed","REA Verified"];
const fields:ImportField[]=[
 {key:"status",label:"Submission Status",managed:true},{key:"id",label:"External ID (Serial No)"},{key:"customerId",label:"Customer ID"},
 {key:"customerName",label:"Customer Name"},{key:"gender",label:"Gender of Primary Account Holder"},{key:"customerCategory",label:"Customer Category"},
 {key:"customerType",label:"Customer Type"},{key:"address",label:"Location (Address)"},{key:"state",label:"Location (State)"},
 {key:"lga",label:"Location (LGA)"},{key:"phone",label:"Phone Number"},{key:"alternatePhone",label:"Alternate phone number"},
 {key:"latitude",label:"Latitude"},{key:"longitude",label:"Longitude"},{key:"paymentDate",label:"Payment Date"},{key:"model",label:"Model"},
 {key:"pvCapacity",label:"PV Capacity (W)"},{key:"paymentType",label:"Type of Payment"},{key:"retailCost",label:"Retail Cost of System (NGN)"},
 {key:"costToEndUser",label:"Cost to End User (NGN)"},{key:"paymentPlan",label:"Payment Plan"},{key:"downpayment",label:"Downpayment Amount (NGN)"},
 {key:"installment",label:"Installment Amount (NGN)"},{key:"submittedDate",label:"Submitted Date",managed:true},
 {key:"auditStatus",label:"Audit Status",managed:true},{key:"auditorNotes",label:"Auditor Notes",managed:true},
 {key:"approvedDate",label:"Approved Date",managed:true},{key:"paidDate",label:"Paid Date",managed:true},{key:"uploadDate",label:"Upload Date",managed:true},
];
const sampleBase=[
 ["DARES-SHS-260001","CUS-KD-10482","Amina Ibrahim","Female","Household","Residential","House 14, blue gate beside Community Primary School","Kaduna","Chikun","08031245678","07051823461",10.46281,7.43214,"2026-08-12","Sunking Home 200X",200,"Mobile Money",285000,215000,"Pay-as-you-go",35000,15000,"Northlight Renewable Energy Ltd"],
 ["DARES-SHS-260002","CUS-KN-20831","Musa Abdullahi","Male","MSME","Commercial","Shop 8, Yan Kura Market opposite central mosque","Kano","Nassarawa","08067481239","",12.00172,8.53542,"2026-08-14","d.light X200",200,"Bank Transfer",310000,230000,"Installment",50000,30000,"Sahel Solar Solutions"],
 ["DARES-SHS-260003","CUS-OG-31774","Blessing Okafor","Female","Household","Residential","Cream bungalow behind Asero Health Centre","Ogun","Abeokuta South","08129034751","09064021873",7.12431,3.35892,"2026-08-17","Lumos Eco 250",250,"Card Payment",365000,275000,"Pay-as-you-go",55000,27500,"GreenGrid Energy Services"],
 ["DARES-SHS-260004","CUS-PL-44109","Yakubu Danjuma","Male","Productive Use","Agricultural","Rice mill compound near Mangu motor park","Plateau","Mangu","07039812564","08059173642",9.52067,9.09683,"2026-08-19","Auxano PowerBox 500",500,"Bank Transfer",690000,510000,"Installment",100000,50000,"Northlight Renewable Energy Ltd"],
 ["DARES-SHS-260005","CUS-EN-55218","Ngozi Eze","Female","MSME","Commercial","Tailoring shop beside New Market water tower","Enugu","Enugu North","08024561983","",6.47618,7.50184,"2026-08-21","Sunking Home 300",300,"Cash",445000,330000,"Outright",330000,0,"GreenGrid Energy Services"],
 ["DARES-SHS-260006","CUS-BA-66702","Sadiq Mohammed","Male","Household","Residential","Block C, staff quarters behind General Hospital","Bauchi","Bauchi","08167392045","07011239854",10.31041,9.84388,"2026-08-22","d.light X500",500,"Mobile Money",725000,545000,"Pay-as-you-go",95000,45000,"Sahel Solar Solutions"],
] as const;
const seeded:Claim[]=sampleBase.map((row,index)=>({
 id:String(row[0]),customerId:String(row[1]),customerName:String(row[2]),gender:String(row[3]),customerCategory:String(row[4]),customerType:String(row[5]),
 address:String(row[6]),state:String(row[7]),lga:String(row[8]),phone:String(row[9]),alternatePhone:String(row[10]),latitude:Number(row[11]),longitude:Number(row[12]),
 paymentDate:String(row[13]),model:String(row[14]),pvCapacity:Number(row[15]),paymentType:String(row[16]),retailCost:Number(row[17]),costToEndUser:Number(row[18]),
 paymentPlan:String(row[19]),downpayment:Number(row[20]),installment:Number(row[21]),contractor:String(row[22]),submittedDate:`2026-08-${String(23-index).padStart(2,"0")}`,
 auditStatus:index<2?"Approved":index===2?"In Review":"Pending Audit",auditorNotes:index===0?"Customer and installation evidence confirmed.":"",
 approvedDate:index<2?`2026-08-${String(24-index).padStart(2,"0")}`:"",paidDate:index===0?"2026-08-25":"",uploadDate:"2026-08-23",
 consultant:index<3?"Oyelaran & Co":"Unassigned",status:index===0?"REA Verified":index===1?"Consultant Reviewed":index===2?"Assigned for Verification":"Uploaded"
}));
const dropdowns={
 gender:["Female","Male","Prefer not to say"],customerCategory:["Household","MSME","Productive Use","Public Facility"],
 customerType:["Residential","Commercial","Agricultural","Institutional"],paymentType:["Cash","Bank Transfer","Mobile Money","Card Payment"],
 paymentPlan:["Outright","Installment","Pay-as-you-go"],
};
function readClaims(){try{const raw=localStorage.getItem(storageKey);const parsed=raw?JSON.parse(raw):seeded;return Array.isArray(parsed)&&parsed.length?parsed as Claim[]:seeded}catch{return seeded}}
function money(value:number){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(value)}
function csvCell(value:unknown){return `"${String(value??"").replace(/"/g,'""')}"`}
function normal(value:string){return value.toLowerCase().replace(/[^a-z0-9]/g,"")}
function parseCsvLine(line:string){const out:string[]=[];let cell="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){cell+='"';i++}else if(ch==='"')quoted=!quoted;else if(ch===","&&!quoted){out.push(cell.trim());cell=""}else cell+=ch}out.push(cell.trim());return out}
function parseRows(text:string){if(/<table[\s>]/i.test(text)){const doc=new DOMParser().parseFromString(text,"text/html");return [...doc.querySelectorAll("tr")].map(row=>[...row.querySelectorAll("th,td")].map(cell=>(cell.textContent||"").trim()))}return text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean).map(parseCsvLine)}
function excelDate(value:string){if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const parsed=new Date(value);return Number.isNaN(parsed.getTime())?"":parsed.toISOString().slice(0,10)}
function makeClaim(raw:Record<string,string>,row:number):Claim{
 const value=(key:keyof Claim)=>raw[key]??"";
 const number=(key:keyof Claim)=>Number(value(key).replace(/[^0-9.-]/g,""))||0;
 return{id:value("id"),customerId:value("customerId"),customerName:value("customerName"),gender:value("gender"),customerCategory:value("customerCategory"),customerType:value("customerType"),
 address:value("address"),state:value("state"),lga:value("lga"),phone:value("phone"),alternatePhone:value("alternatePhone"),latitude:number("latitude"),longitude:number("longitude"),
 paymentDate:excelDate(value("paymentDate")),model:value("model"),pvCapacity:number("pvCapacity"),paymentType:value("paymentType"),retailCost:number("retailCost"),costToEndUser:number("costToEndUser"),
 paymentPlan:value("paymentPlan"),downpayment:number("downpayment"),installment:number("installment"),submittedDate:new Date().toISOString().slice(0,10),auditStatus:"Pending Audit",
 auditorNotes:"",approvedDate:"",paidDate:"",uploadDate:new Date().toISOString().slice(0,10),contractor:value("contractor")||"Uploaded Contractor",
 consultant:"Unassigned",status:"Uploaded"};
}
function validate(claim:Claim,row:number,existing:Set<string>,coordinates:Set<string>):StageRow{
 const issues:string[]=[];let validity:"Valid"|"Flagged"|"Error"="Valid";const error=(message:string)=>{issues.push(message);validity="Error"};const flag=(message:string)=>{issues.push(message);if(validity!=="Error")validity="Flagged"};
 if(!claim.id)error("External ID is required");else if(existing.has(claim.id))error("Duplicate External ID / serial number");
 if(!claim.customerId)error("Customer ID is required");if(!claim.customerName)error("Customer name is required");
 if(!claim.address||claim.address.length<12)flag("Address needs building features, street and nearest landmark");
 if(!claim.state||!claim.lga)error("State and LGA are required");
 if(!/^\+?\d{10,14}$/.test(claim.phone.replace(/[\s-]/g,"")))error("Valid customer phone number is required");
 if(!Number.isFinite(claim.latitude)||claim.latitude<-90||claim.latitude>90||!Number.isFinite(claim.longitude)||claim.longitude<-180||claim.longitude>180||(claim.latitude===0&&claim.longitude===0))error("Latitude or longitude is missing/invalid");
 const coordinate=`${claim.latitude.toFixed(6)},${claim.longitude.toFixed(6)}`;if(coordinates.has(coordinate))error("Coordinates must be unique to this installation");else coordinates.add(coordinate);
 if(!claim.paymentDate)error("Payment date is missing or invalid");if(!claim.model)error("Approved system model is required");if(claim.pvCapacity<=0)error("PV capacity must be greater than zero");
 if(claim.retailCost<=0)error("Retail cost is missing or malformed");if(claim.costToEndUser<=0)error("Cost to end user is missing or malformed");if(claim.costToEndUser>claim.retailCost)flag("Cost to end user exceeds retail system cost");
 if(!claim.paymentPlan)error("Payment plan is required");if(claim.paymentPlan!=="Outright"&&claim.downpayment<=0)flag("Downpayment is missing for the selected payment plan");
 return{...claim,row,validity,issues};
}
function tone(status:ClaimStatus){if(status==="REA Verified")return"border-emerald-200 bg-emerald-50 text-emerald-700";if(status==="Rejected"||status==="Disputed")return"border-rose-200 bg-rose-50 text-rose-700";if(status==="Uploaded")return"border-slate-200 bg-slate-100 text-slate-600";return"border-blue-200 bg-blue-50 text-blue-700"}

export default function ReaClaimsManagement(){
 const[claims,setClaims]=useState<Claim[]>(readClaims);const[selected,setSelected]=useState<Claim|null>(null);const[showImport,setShowImport]=useState(false);
 const[staged,setStaged]=useState<StageRow[]>([]);const[notice,setNotice]=useState("");const[syncing,setSyncing]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 const[filters,setFilters]=useState({q:"",state:"All",contractor:"All",assignment:"All",audit:"All"});
 const consultants=readConsultants().filter(consultant=>consultant.status==="Active");
 const persist=(next:Claim[])=>{setClaims(next);localStorage.setItem(storageKey,JSON.stringify(next))};
 const visible=useMemo(()=>claims.filter(claim=>(!filters.q||`${claim.id} ${claim.customerId} ${claim.customerName} ${claim.model}`.toLowerCase().includes(filters.q.toLowerCase()))&&(filters.state==="All"||claim.state===filters.state)&&(filters.contractor==="All"||claim.contractor===filters.contractor)&&(filters.audit==="All"||claim.auditStatus===filters.audit)&&(filters.assignment==="All"||(filters.assignment==="Assigned"?claim.consultant!=="Unassigned":claim.consultant==="Unassigned"))),[claims,filters]);
 const options=(key:"state"|"contractor"|"auditStatus")=>[...new Set(claims.map(claim=>claim[key]).filter(Boolean))].sort();
 const downloadTemplate=()=>{const headings=[...fields.map(field=>field.label),"Contractor / Developer"];const samples=seeded.slice(0,3).map(claim=>[...fields.map(field=>field.managed?"":claim[field.key]),claim.contractor]);const html=`<!doctype html><html><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Arial;font-size:10pt}th{background:#08733f;color:white;font-weight:bold}th,td{border:1px solid #cbd5e1;padding:7px;white-space:nowrap}.note{background:#fff4cc}</style></head><body><table><tr>${headings.map(heading=>`<th>${heading}</th>`).join("")}</tr>${samples.map(row=>`<tr>${row.map((cell,index)=>`<td${fields[index]?.managed?' class="note"':""}>${String(cell??"")}</td>`).join("")}</tr>`).join("")}</table></body></html>`;const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([html],{type:"application/vnd.ms-excel"}));link.download="DARES-Supply-Side-Claims-Template.xls";link.click();URL.revokeObjectURL(link.href)};
 const upload=async(file?:File)=>{if(!file)return;const text=await file.text();if(text.startsWith("PK")){setNotice("Please use the downloadable .xls template or save the workbook as CSV before uploading.");return}const rows=parseRows(text).filter(row=>row.some(Boolean));if(rows.length<2){setNotice("The workbook has no claim rows.");return}const header=rows[0].map(normal);const rawFields=new Map(fields.map(field=>[normal(field.label),field.key]));rawFields.set(normal("Contractor / Developer"),"contractor");if(!header.includes(normal("External ID (Serial No)"))||!header.includes(normal("Customer ID"))){setNotice("Invalid claim workbook. Download the DARES template and preserve its column headings.");return}const existing=new Set(claims.map(claim=>claim.id));const coordinates=new Set(claims.map(claim=>`${claim.latitude.toFixed(6)},${claim.longitude.toFixed(6)}`));const parsed=rows.slice(1).map((values,index)=>{const raw:Record<string,string>={};header.forEach((heading,column)=>{const key=rawFields.get(heading);if(key)raw[key]=values[column]??""});return validate(makeClaim(raw,index+2),index+2,existing,coordinates)});setStaged(parsed);setShowImport(true)};
 const editStage=(index:number,key:keyof Claim,value:string)=>setStaged(current=>{const draft=current.map((row,i)=>i===index?{...row,[key]:["latitude","longitude","pvCapacity","retailCost","costToEndUser","downpayment","installment"].includes(key)?Number(value):value}:row);const existing=new Set(claims.map(claim=>claim.id));const coordinates=new Set(claims.map(claim=>`${claim.latitude.toFixed(6)},${claim.longitude.toFixed(6)}`));return draft.map(row=>validate(row,row.row,existing,coordinates))});
 const commitImport=()=>{const ready=staged.filter(row=>row.validity==="Valid");persist([...ready.map(({row,validity,issues,...claim})=>claim),...claims]);setStaged([]);setShowImport(false);setNotice(`${ready.length} validated DARES claims imported successfully.`)};
 const assign=(claim:Claim,firm:string)=>{const updated={...claim,consultant:firm,status:"Assigned for Verification" as ClaimStatus};persist(claims.map(item=>item.id===claim.id?updated:item));setSelected(updated);setNotice(`${firm} assigned to ${claim.id}.`)};
 const syncFromApi=async()=>{if(!apiBase){setNotice("REA API endpoint is not configured yet. Set VITE_REA_CLAIMS_API_URL in the deployment environment.");return}setSyncing(true);try{const response=await fetch(`${apiBase}/claims`,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error(`REA API returned ${response.status}`);const payload=await response.json();const incoming=Array.isArray(payload)?payload:Array.isArray(payload?.claims)?payload.claims:[];const valid=incoming.filter((item:any)=>item&&typeof item.id==="string"&&typeof item.customerId==="string") as Claim[];persist([...valid,...claims.filter(local=>!valid.some(remote=>remote.id===local.id))]);setNotice(`${valid.length} claims synchronized from the REA system.`)}catch(error){setNotice(error instanceof Error?error.message:"Unable to connect to the REA claims API.")}finally{setSyncing(false)}};
 const summary={total:claims.length,value:claims.reduce((sum,claim)=>sum+claim.costToEndUser,0),assigned:claims.filter(claim=>claim.consultant!=="Unassigned").length,unassigned:claims.filter(claim=>claim.consultant==="Unassigned").length};

 if(selected)return <ClaimDetail claim={selected} consultants={consultants.map(consultant=>consultant.firmName)} onBack={()=>setSelected(null)} onAssign={firm=>assign(selected,firm)}/>;
 return <div className="space-y-4 pb-8 pt-4">
  <section className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><CircleDollarSign className="h-5 w-5 text-[#08733f]"/><h2 className="text-xl font-bold text-[#173b2a]">DARES Claims Management</h2></div><p className="mt-1 text-xs text-slate-500">Upload and validate contractor supply-side subsidy claims for customer-level verification.</p></div><div className="flex gap-2"><button onClick={downloadTemplate} className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 px-4 text-xs font-bold text-slate-700 hover:bg-slate-50"><Download className="h-4 w-4"/>Download XLS template</button><button onClick={()=>fileRef.current?.click()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#08733f] px-4 text-xs font-bold text-white hover:bg-[#065d32]"><Upload className="h-4 w-4"/>Upload XLS/CSV</button><input ref={fileRef} hidden type="file" accept=".csv,.xls,text/csv,application/vnd.ms-excel" onChange={event=>void upload(event.target.files?.[0])}/></div></section>
  {notice&&<div className="flex items-center justify-between rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-700"><span>{notice}</span><button onClick={()=>setNotice("")}><XCircle className="h-4 w-4"/></button></div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[FileSpreadsheet,"Claims Submitted",summary.total,"Customer installations uploaded"],[Banknote,"End-user Value",money(summary.value),"Combined cost to end users"],[UserRoundCheck,"Assigned for Inspection",summary.assigned,summary.total?Math.round(summary.assigned/summary.total*100)+"% of submitted claims":"No claims submitted"],[AlertTriangle,"Awaiting Assignment",summary.unassigned,summary.unassigned?"Requires consultant assignment":"No assignment backlog"]].map(([Icon,label,value,detail]:any)=><article key={label} className="group min-h-[108px] rounded-lg border border-slate-200 bg-white p-4 text-center shadow-sm transition hover:-translate-y-0.5 hover:border-[#9dceb0] hover:shadow-md"><div className="flex h-full flex-col items-center justify-center"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-50 text-[#08733f] transition group-hover:bg-[#08733f] group-hover:text-white"><Icon className="h-5 w-5"/></div><p className="mt-2 text-sm font-semibold text-[#263c31]">{label}</p><p className="mt-1 text-xl font-bold text-[#13281e]">{value}</p><p className="mt-1 text-[10px] text-slate-500">{detail}</p></div></article>)}</section>
  <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-lg ${apiBase?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{apiBase?<Cloud className="h-5 w-5"/>:<WifiOff className="h-5 w-5"/>}</div><div><h3 className="text-sm font-bold text-[#173b2a]">REA system API</h3><p className="mt-1 text-[11px] text-slate-500">{apiBase?"Endpoint configured — ready to synchronize DARES claims.":"Connection provisioned. Configure VITE_REA_CLAIMS_API_URL for the production REA system."}</p></div></div><button onClick={()=>void syncFromApi()} disabled={syncing} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 text-xs font-bold text-[#08733f] hover:bg-[#08733f] hover:text-white disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${syncing?"animate-spin":""}`}/>{syncing?"Synchronizing…":"Sync REA claims"}</button></div></section>
  <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center gap-2 text-xs font-bold text-[#173b2a]"><Filter className="h-4 w-4 text-[#08733f]"/>Claim filters</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><label className="relative lg:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={filters.q} onChange={event=>setFilters({...filters,q:event.target.value})} placeholder="Serial number, customer, ID or model" className="h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-xs"/></label><select value={filters.state} onChange={event=>setFilters({...filters,state:event.target.value})} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs"><option>All</option>{options("state").map(value=><option key={value}>{value}</option>)}</select><select value={filters.contractor} onChange={event=>setFilters({...filters,contractor:event.target.value})} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs"><option>All</option>{options("contractor").map(value=><option key={value}>{value}</option>)}</select><select value={filters.assignment} onChange={event=>setFilters({...filters,assignment:event.target.value})} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs"><option>All</option><option>Assigned</option><option>Unassigned</option></select></div></section>
  <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="text-sm font-bold text-[#173b2a]">Claims register</h3><p className="mt-1 text-[10px] text-slate-500">{visible.length} customer installation claims</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1280px] text-left"><thead className="bg-slate-50 text-[9px] font-bold uppercase tracking-wider text-slate-500"><tr>{["External ID","Customer","State / LGA","System / PV","Cost to End User","Payment Date","Contractor / Developer","Audit","Assignment","Actions"].map(heading=><th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody>{visible.map(claim=><tr key={claim.id} className="border-t border-slate-100 hover:bg-[#f8fcf9]"><td className="px-4 py-4"><p className="text-xs font-bold text-[#08733f]">{claim.id}</p><p className="mt-1 text-[9px] text-slate-400">{claim.customerId}</p></td><td className="px-4 py-4"><p className="text-xs font-semibold text-slate-700">{claim.customerName}</p><p className="mt-1 text-[9px] text-slate-400">{claim.phone}</p></td><td className="px-4 py-4 text-xs">{claim.state}<small className="block text-[9px] text-slate-400">{claim.lga}</small></td><td className="px-4 py-4"><p className="text-xs font-semibold">{claim.model}</p><p className="mt-1 text-[9px] text-slate-400">{claim.pvCapacity.toLocaleString()} W</p></td><td className="px-4 py-4 text-xs font-bold">{money(claim.costToEndUser)}</td><td className="px-4 py-4 text-xs">{claim.paymentDate}</td><td className="px-4 py-4 text-xs">{claim.contractor}</td><td className="px-4 py-4"><span className="whitespace-nowrap rounded-full bg-blue-50 px-2 py-1 text-[9px] font-bold text-blue-700">{claim.auditStatus}</span></td><td className="px-4 py-4"><span className={`whitespace-nowrap rounded-full border px-2.5 py-1 text-[9px] font-bold ${claim.consultant==="Unassigned"?"border-amber-200 bg-amber-50 text-amber-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{claim.consultant==="Unassigned"?"Unassigned":"Assigned"}</span></td><td className="px-4 py-4"><button onClick={()=>setSelected(claim)} className="inline-flex items-center gap-1 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-[10px] font-bold text-[#08733f] hover:bg-[#08733f] hover:text-white">View<ChevronRight className="h-3.5 w-3.5"/></button></td></tr>)}</tbody></table></div></section>
  {showImport&&<ImportModal rows={staged} onClose={()=>{setShowImport(false);setStaged([])}} onEdit={editStage} onCommit={commitImport}/>}
 </div>;
}

function ImportModal({rows,onClose,onEdit,onCommit}:{rows:StageRow[];onClose:()=>void;onEdit:(index:number,key:keyof Claim,value:string)=>void;onCommit:()=>void}){
 const valid=rows.filter(row=>row.validity==="Valid").length,flagged=rows.filter(row=>row.validity==="Flagged").length,errors=rows.filter(row=>row.validity==="Error").length;
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/45 p-4"><section className="max-h-[92vh] w-full max-w-7xl overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b p-5"><div><h3 className="text-lg font-bold text-[#173b2a]">DARES import validation</h3><p className="mt-1 text-xs text-slate-500">{rows.length} rows processed — {valid} valid, {flagged} flagged, {errors} error{errors===1?"":"s"}</p></div><button onClick={onClose}><XCircle className="h-5 w-5"/></button></header><div className="grid grid-cols-3 gap-3 border-b bg-slate-50 p-4">{[["Valid",valid,"text-emerald-700"],["Flagged",flagged,"text-amber-700"],["Errors",errors,"text-rose-700"]].map(([label,value,colour]:any)=><div key={label} className="rounded-lg bg-white p-3 text-center"><strong className={`text-xl ${colour}`}>{value}</strong><p className="text-[10px] text-slate-500">{label}</p></div>)}</div><div className="max-h-[55vh] overflow-auto"><table className="w-full min-w-[1450px]"><thead className="sticky top-0 bg-white text-left text-[9px] uppercase text-slate-500"><tr>{["Row","External ID","Customer ID","Customer Name","Latitude","Longitude","Model","PV (W)","Cost to End User","Result"].map(label=><th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.row} className="border-t align-top"><td className="p-3 text-xs">{row.row}</td>{([["id",row.id,"w-44"],["customerId",row.customerId,"w-36"],["customerName",row.customerName,"w-44"],["latitude",row.latitude,"w-28"],["longitude",row.longitude,"w-28"],["model",row.model,"w-44"],["pvCapacity",row.pvCapacity,"w-24"],["costToEndUser",row.costToEndUser,"w-32"]] as [keyof Claim,string|number,string][]).map(([key,value,width])=><td key={key} className="p-2"><input value={value} onChange={event=>onEdit(index,key,event.target.value)} className={`h-9 rounded border px-2 text-xs ${width}`}/></td>)}<td className="p-3"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${row.validity==="Valid"?"bg-emerald-50 text-emerald-700":row.validity==="Flagged"?"bg-amber-50 text-amber-700":"bg-rose-50 text-rose-700"}`}>{row.validity}</span>{row.issues.map(issue=><p key={issue} className="mt-1 max-w-64 text-[9px] text-slate-500">{issue}</p>)}</td></tr>)}</tbody></table></div><footer className="flex items-center justify-between border-t p-4"><p className="text-[10px] text-slate-500">Correct flagged and invalid rows inline before final commit.</p><div className="flex gap-2"><button onClick={onClose} className="rounded-lg border px-4 py-2 text-xs font-bold">Cancel</button><button onClick={onCommit} disabled={errors>0||flagged>0} className="rounded-lg bg-[#08733f] px-4 py-2 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Commit validated claims</button></div></footer></section></div>;
}

function ClaimDetail({claim,consultants,onBack,onAssign}:{claim:Claim;consultants:string[];onBack:()=>void;onAssign:(firm:string)=>void}){
 const index=Math.max(0,lifecycle.indexOf(claim.status));
 const details=[[UserRoundCheck,"Customer",claim.customerName],[Phone,"Phone",claim.phone],[MapPin,"Location",`${claim.state}, ${claim.lga}`],[PackageCheck,"Model",claim.model],[Zap,"PV Capacity",`${claim.pvCapacity.toLocaleString()} W`],[Banknote,"Cost to End User",money(claim.costToEndUser)],[CalendarDays,"Payment Date",claim.paymentDate],[ShieldCheck,"Audit",claim.auditStatus]];
 return <div className="space-y-4 pb-8 pt-4"><button onClick={onBack} className="inline-flex items-center gap-2 text-xs font-bold text-slate-600 hover:text-[#08733f]"><ArrowLeft className="h-4 w-4"/>Claims register</button><section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#08733f]">DARES supply-side subsidy claim</p><h2 className="mt-1 text-xl font-bold text-[#173b2a]">{claim.id}</h2><p className="mt-1 text-xs text-slate-500">{claim.customerId} · {claim.contractor}</p></div><span className={`rounded-full border px-3 py-1.5 text-[10px] font-bold ${tone(claim.status)}`}>{claim.status}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{details.map(([Icon,label,value]:any)=><div key={label} className="rounded-lg bg-slate-50 p-4"><Icon className="h-4 w-4 text-[#08733f]"/><p className="mt-2 text-[10px] text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-[#173b2a]">{value}</p></div>)}</div></section>
 <section className="rounded-xl border bg-white p-5 shadow-sm"><h3 className="text-sm font-bold text-[#173b2a]">Claim status lifecycle</h3><div className="mt-5 grid gap-2 lg:grid-cols-5">{lifecycle.map((stage,position)=><div key={stage} className={`rounded-lg border p-3 ${position<=index?"border-emerald-200 bg-emerald-50":"border-slate-200 bg-slate-50"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full text-[10px] font-bold ${position<=index?"bg-[#08733f] text-white":"bg-slate-200 text-slate-500"}`}>{position<index?<CheckCircle2 className="h-3.5 w-3.5"/>:position+1}</span><p className="mt-2 text-[10px] font-bold text-slate-700">{stage}</p></div>)}</div></section>
 <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-xl border bg-white p-5"><h3 className="text-sm font-bold text-[#173b2a]">Inspection assignment</h3><div className={`mt-3 rounded-lg border p-3 ${claim.consultant==="Unassigned"?"border-amber-200 bg-amber-50":"border-emerald-200 bg-emerald-50"}`}><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Assignment status</p><p className={`mt-1 text-sm font-bold ${claim.consultant==="Unassigned"?"text-amber-700":"text-emerald-700"}`}>{claim.consultant==="Unassigned"?"Unassigned":`Assigned to ${claim.consultant}`}</p></div><select defaultValue="" onChange={event=>event.target.value&&onAssign(event.target.value)} className="mt-4 h-10 w-full rounded-lg border bg-white px-3 text-xs"><option value="">Assign an active consultant…</option>{consultants.map(consultant=><option key={consultant}>{consultant}</option>)}</select></article>
 <article className="rounded-xl border bg-white p-5"><h3 className="text-sm font-bold text-[#173b2a]">Payment & installation</h3><dl className="mt-3 space-y-3 text-xs">{[["Retail cost",money(claim.retailCost)],["Payment type",claim.paymentType],["Payment plan",claim.paymentPlan],["Downpayment",money(claim.downpayment)],["Installment",money(claim.installment)],["Coordinates",`${claim.latitude}, ${claim.longitude}`]].map(([label,value])=><div key={label} className="flex justify-between gap-4"><dt className="text-slate-500">{label}</dt><dd className="text-right font-bold">{value}</dd></div>)}</dl></article></section>
 <section className="rounded-xl border bg-white p-5"><h3 className="text-sm font-bold text-[#173b2a]">Customer and audit record</h3><div className="mt-4 grid gap-4 text-xs md:grid-cols-2"><div><p className="font-bold text-slate-700">{claim.address}</p><p className="mt-2 text-slate-500">{claim.gender} · {claim.customerCategory} · {claim.customerType}</p><p className="mt-1 text-slate-500">Alternate phone: {claim.alternatePhone||"Not supplied"}</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="font-bold text-[#173b2a]">{claim.auditStatus}</p><p className="mt-2 text-slate-500">{claim.auditorNotes||"No auditor notes recorded."}</p><p className="mt-2 text-[10px] text-slate-400">Uploaded {claim.uploadDate} · Approved {claim.approvedDate||"—"} · Paid {claim.paidDate||"—"}</p></div></div></section></div>;
}
