import { useMemo, useState } from "react";
import {
  BarChart3, Building2, CalendarDays, CheckCircle2, ClipboardCheck, Download,
  FileBarChart, FileCheck2, FileText, Map, MapPinned, RefreshCw, Search, ShieldCheck,
} from "lucide-react";
import type { Project } from "../lib/dashboard-data";

type ReportDefinition={id:string;title:string;description:string;icon:any;tone:string;includes:string[]};
const definitions:ReportDefinition[]=[
 {id:"inspection",title:"Individual Inspection Report",description:"Complete evidence, coordinates, technical findings and review decisions for a single field inspection.",icon:ClipboardCheck,tone:"emerald",includes:["Inspection details","Evidence register","QA decisions"]},
 {id:"project",title:"Project Summary Report",description:"Executive summary of project scope, delivery, capacity, households reached and verification position.",icon:FileText,tone:"blue",includes:["Project profile","Delivery metrics","Verification status"]},
 {id:"contractor",title:"Contractor Performance Report",description:"Compare contractor delivery volume, completion quality, verification rate and outstanding actions.",icon:Building2,tone:"violet",includes:["Delivery ranking","Quality signals","Pending actions"]},
 {id:"state",title:"State Performance Report",description:"State-level programme delivery, installed capacity, impact and verification performance.",icon:Map,tone:"emerald",includes:["State portfolio","Capacity & impact","Programme split"]},
 {id:"lga",title:"LGA Performance Report",description:"Detailed local-government delivery coverage, project progress and unresolved verification items.",icon:MapPinned,tone:"blue",includes:["LGA coverage","Project register","Verification backlog"]},
 {id:"reinspection",title:"Re-inspection Report",description:"Track rejected submissions, reasons for return, corrective actions and repeat inspection outcomes.",icon:RefreshCw,tone:"amber",includes:["Return reasons","Corrective actions","Resolution status"]},
 {id:"progress",title:"Project Progress Report",description:"Monitor planned versus delivered milestones, field activity, report submission and completion trend.",icon:BarChart3,tone:"rose",includes:["Milestones","Progress trend","Delivery exceptions"]},
];
const toneClass=(tone:string)=>tone==="blue"?"bg-blue-50 text-blue-700":tone==="violet"?"bg-violet-50 text-violet-700":tone==="amber"?"bg-amber-50 text-amber-700":tone==="rose"?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700";
export default function ReaReportsManagement({projects}:{projects:Project[]}){
 const[selected,setSelected]=useState<ReportDefinition>(definitions[0]);const[programme,setProgramme]=useState("All");const[state,setState]=useState("All");const[period,setPeriod]=useState("All periods");const[query,setQuery]=useState("");const[notice,setNotice]=useState("");
 const programmes=useMemo(()=>["All",...new Set(projects.map(p=>p.programme))],[projects]),states=useMemo(()=>["All",...new Set(projects.map(p=>p.state))],[projects]);
 const matching=useMemo(()=>projects.filter(p=>(programme==="All"||p.programme===programme)&&(state==="All"||p.state===state)&&(!query||p.name.toLowerCase().includes(query.toLowerCase()))),[projects,programme,state,query]);
 const totals={records:matching.length,verified:matching.filter(p=>p.verified).length,pending:matching.filter(p=>!p.verified).length,reportTypes:definitions.length};
 const exportCsv=()=>{const rows=[["Project","Programme","State","Component","Contractor","Status","Capacity kW","Households"],...matching.map(p=>[p.name,p.programme,p.state,p.component,p.contractor,p.status,String(p.kw),String(p.households)])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=selected.id+"-report.csv";a.click();URL.revokeObjectURL(a.href);setNotice(selected.title+" exported successfully.")};
 const generate=()=>{setNotice(selected.title+" generated for "+matching.length+" matching projects.");window.setTimeout(()=>window.print(),250)};
 return <div className="space-y-4 pb-8 pt-4">
  <section className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><FileBarChart className="h-5 w-5 text-[#08733f]"/><h2 className="text-xl font-bold text-[#173b2a]">Reports Centre</h2></div><p className="mt-1 text-xs text-slate-500">Generate consistent inspection, delivery and performance reports for REA decision-making.</p></div><div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-[10px] font-bold text-emerald-700"><ShieldCheck className="h-4 w-4"/>Verified data controls applied</div></section>
  {notice&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-700">{notice}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[FileBarChart,"Report Templates",totals.reportTypes,"Approved report formats"],[FileCheck2,"Report Records",totals.records.toLocaleString(),"Records in the current scope"],[ShieldCheck,"Ready to Issue",totals.verified.toLocaleString(),"Verified records available"],[RefreshCw,"Require Review",totals.pending.toLocaleString(),"Records not yet report-ready"]].map(([Icon,label,value,detail]:any)=><article key={label} className="group min-h-[112px] rounded-lg border border-slate-200 bg-white p-4 text-center shadow-[0_1px_2px_rgba(16,24,40,0.04)] transition-all duration-200 hover:-translate-y-0.5 hover:border-[#9dceb0] hover:shadow-md"><div className="flex h-full flex-col items-center justify-center"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-50 text-[#08733f] transition-all duration-200 group-hover:bg-[#08733f] group-hover:text-white"><Icon className="h-5 w-5 transition-transform duration-200 group-hover:scale-110"/></div><p className="mt-2 text-sm font-semibold text-[#263c31]">{label}</p><p className="mt-1 text-[23px] font-bold leading-none tracking-tight text-[#13281e]">{value}</p><p className="mt-2 text-[11px] text-slate-500">{detail}</p></div></article>)}</section>
  <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="relative xl:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search project for report scope" className="h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-xs"/></label><select value={programme} onChange={e=>setProgramme(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-600">{programmes.map(x=><option key={x}>{x}</option>)}</select><select value={state} onChange={e=>setState(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-600">{states.map(x=><option key={x}>{x}</option>)}</select><select value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-600"><option>All periods</option><option>Current month</option><option>Current quarter</option><option>Year to date</option><option>Custom period</option></select></div></section>
  <section className="grid gap-4 xl:grid-cols-[1.5fr_.75fr]"><div className="grid gap-3 sm:grid-cols-2">{definitions.map((report,index)=>{const Icon=report.icon,active=selected.id===report.id;return <button key={report.id} onClick={()=>setSelected(report)} className={"group rounded-xl border p-4 text-left shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md "+(active?"border-[#08733f] bg-[#f3fbf5] ring-1 ring-[#08733f]/10":"border-slate-200 bg-white hover:border-[#9dceb0]")}><div className="flex items-start gap-3"><span className={"flex h-10 w-10 shrink-0 items-center justify-center rounded-xl transition group-hover:bg-[#08733f] group-hover:text-white "+toneClass(report.tone)}><Icon className="h-5 w-5"/></span><div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Report {index+1}</p><h3 className="mt-1 text-sm font-bold text-[#173b2a]">{report.title}</h3><p className="mt-2 text-[10px] leading-4 text-slate-500">{report.description}</p><div className="mt-3 flex flex-wrap gap-1.5">{report.includes.map(x=><span key={x} className="rounded-full bg-slate-100 px-2 py-1 text-[8px] font-semibold text-slate-500">{x}</span>)}</div></div></div></button>})}</div>
   <aside className="h-fit rounded-xl border border-slate-200 bg-white p-5 shadow-sm xl:sticky xl:top-[110px]"><div className={"flex h-12 w-12 items-center justify-center rounded-xl "+toneClass(selected.tone)}>{(() => {const Icon=selected.icon;return <Icon className="h-6 w-6"/>})()}</div><p className="mt-4 text-[9px] font-bold uppercase tracking-wider text-[#08733f]">Selected report</p><h3 className="mt-1 text-lg font-bold text-[#173b2a]">{selected.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{selected.description}</p><dl className="mt-5 divide-y divide-slate-100 text-xs"><div className="flex justify-between py-3"><dt className="text-slate-500">Programme</dt><dd className="font-bold">{programme}</dd></div><div className="flex justify-between py-3"><dt className="text-slate-500">State</dt><dd className="font-bold">{state}</dd></div><div className="flex justify-between py-3"><dt className="text-slate-500">Period</dt><dd className="font-bold">{period}</dd></div><div className="flex justify-between py-3"><dt className="text-slate-500">Records</dt><dd className="font-bold">{matching.length}</dd></div></dl><button onClick={generate} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#08733f] text-xs font-bold text-white hover:bg-[#065d32]"><FileText className="h-4 w-4"/>Generate PDF / Print</button><button onClick={exportCsv} className="mt-2 flex h-11 w-full items-center justify-center gap-2 rounded-lg border border-slate-200 text-xs font-bold text-slate-700 hover:bg-slate-50"><Download className="h-4 w-4"/>Export report data</button></aside>
  </section>
 </div>
}
