import { useState } from "react";
import { BadgeCheck, ClipboardCheck, FileSearch, RotateCcw } from "lucide-react";
import { useInspectionWorkflow } from "../lib/inspection-workflow";

function statusClass(status:string){return "rea-v-status rea-v-status-"+status.toLowerCase().replace(/[^a-z]+/g,"-");}

export default function ReaVerificationManagement(){
  const {assignments,reaReviewReport}=useInspectionWorkflow();
  const [,refresh]=useState(0);
  const rows=assignments.filter((item)=>["Submitted","Approved","Verified","Re-inspection"].includes(item.status)).sort((a,b)=>({Approved:0,Submitted:1,"Re-inspection":2,Verified:3}[a.status as "Approved"|"Submitted"|"Re-inspection"|"Verified"]??9)-({Approved:0,Submitted:1,"Re-inspection":2,Verified:3}[b.status as "Approved"|"Submitted"|"Re-inspection"|"Verified"]??9));
  const counts={approved:assignments.filter((item)=>item.status==="Approved").length,submitted:assignments.filter((item)=>item.status==="Submitted").length,verified:assignments.filter((item)=>item.status==="Verified").length,reinspection:assignments.filter((item)=>item.status==="Re-inspection").length};
  const decide=(id:string,decision:"Verified"|"Re-inspection")=>{
    const note=window.prompt(decision==="Verified"?"Optional REA verification note":"Reason for rejection / re-inspection (required)",decision==="Verified"?"Verified by REA after consultant QA approval.":"");
    if(note===null||decision==="Re-inspection"&&!note.trim())return;
    reaReviewReport(id,decision,note);
  };
  return <section className="rea-v-workspace"><div className="rea-v-shell">
    <div className="rea-v-heading"><div><p className="rea-v-kicker">REA final verification</p><h2>Verification Queue</h2><p>Field Officer submission → Consultant Admin QA → REA approval or rejection. Only Consultant-approved reports can be verified by REA.</p></div><div className="rea-v-flow" aria-label="Verification workflow"><span>Field Officer</span><b>→</b><span>Consultant Admin</span><b>→</b><span className="rea-v-flow-active">REA</span><b>→</b><span>Verified</span></div></div>
    <div className="rea-v-summary"><article className="rea-v-card-approved"><span className="rea-v-icon"><ClipboardCheck aria-hidden="true"/></span><strong>{counts.approved}</strong><small>Awaiting REA</small></article><article className="rea-v-card-submitted"><span className="rea-v-icon"><FileSearch aria-hidden="true"/></span><strong>{counts.submitted}</strong><small>With Consultant QA</small></article><article className="rea-v-card-verified"><span className="rea-v-icon"><BadgeCheck aria-hidden="true"/></span><strong>{counts.verified}</strong><small>Verified</small></article><article className="rea-v-card-warning"><span className="rea-v-icon rea-v-icon-warn"><RotateCcw aria-hidden="true"/></span><strong>{counts.reinspection}</strong><small>Re-inspection</small></article></div>
    <div className="rea-v-table-wrap"><div className="rea-v-table-head"><div><h3>Inspection reports</h3><p>{rows.length} workflow records visible</p></div><button type="button" onClick={()=>refresh((value)=>value+1)}>Refresh queue</button></div><div className="rea-v-table-scroll"><table className="rea-v-table"><thead><tr><th>Project</th><th>Officer</th><th>Consultant stage</th><th>Location</th><th>Evidence</th><th>REA decision</th></tr></thead><tbody>{rows.length?rows.map((item)=><tr key={item.id}><td><strong>{item.projectName}</strong><small>{item.id} · {item.programme} · {item.component}</small></td><td>{item.officer}</td><td><span className={statusClass(item.status)}>{item.status==="Approved"?"Awaiting REA":item.status}</span>{item.report?.reviewNote&&<small className="rea-v-note">{item.report.reviewNote}</small>}</td><td>{item.community}, {item.state}</td><td><strong>{item.report?.evidence?.length||0}</strong> file{(item.report?.evidence?.length||0)===1?"":"s"}</td><td>{item.status==="Approved"?<div className="rea-v-actions"><button type="button" className="rea-v-approve" onClick={()=>decide(item.id,"Verified")}>Approve & Verify</button><button type="button" className="rea-v-reject" onClick={()=>decide(item.id,"Re-inspection")}>Reject</button></div>:<span className="rea-v-readonly">{item.status==="Submitted"?"Waiting for Consultant Admin":item.status==="Verified"?"Finalised":"Returned to Field Officer"}</span>}</td></tr>):<tr><td colSpan={6} className="rea-v-empty">No submitted, approved, verified or re-inspection records are available.</td></tr>}</tbody></table></div></div>
  </div></section>;
}
